# -*- mode: python ; coding: utf-8 -*-

# Iter-171: 添加 slowapi / opentelemetry hidden imports (新工厂级依赖).
# PyInstaller 静态分析可能漏掉这些动态导入的子模块.
# Iter-180: Windows 兼容性增强 — 完整 hidden imports, 静态资源, 可选 GUI 模式.
# Iter-181: 添加更多 Windows 运行时依赖, 优化 onefile 打包.

import sys
import os

# 判断是否为 Windows 平台
IS_WINDOWS = sys.platform == 'win32'

# --- 静态资源 (UI 模板) ---
ui_static_dir = os.path.join(os.path.dirname(os.path.abspath(__spec_file__)), 'f1opt', 'ui', 'static')
ui_datas = []
if os.path.isdir(ui_static_dir):
    for root, dirs, files in os.walk(ui_static_dir):
        for f in files:
            src = os.path.join(root, f)
            dst = os.path.relpath(src, os.path.dirname(ui_static_dir))
            ui_datas.append((src, os.path.dirname(dst)))

a = Analysis(
    ['/workspace/f1opt/cli.py'],
    pathex=[],
    binaries=[],
    datas=ui_datas + [
        # 包含 examples 目录
        ('/workspace/examples', 'examples'),
    ],
    hiddenimports=[
        # --- slowapi (rate limiting) — 动态导入 middleware ---
        'slowapi',
        'slowapi.errors',
        'slowapi.util',
        'slowapi.middleware',
        # --- opentelemetry (tracing) — best-effort, 可选 ---
        'opentelemetry',
        'opentelemetry.api',
        'opentelemetry.sdk',
        'opentelemetry.trace',
        # --- f1opt 新模块 (Iter-170/171) ---
        'f1opt.observability.audit',
        'f1opt.observability.tracing',
        # --- Windows 兼容性: asyncio Windows 事件循环 ---
        'asyncio.windows_events',
        'asyncio.windows_utils',
        'selectors',
        # --- Windows 兼容性: stdlib 底层模块 (Iter-16) ---
        '_queue',
        'queue',
        # --- Windows 兼容性: TLS/SSL 模块 (Iter-17) ---
        '_ssl',
        'ssl',
        # --- Windows 兼容性: stdlib C 扩展模块 (Iter-18~25) ---
        '_hashlib',
        'hashlib',
        '_bisect',
        'bisect',
        '_datetime',
        'datetime',
        '_random',
        'random',
        '_lzma',
        'lzma',
        '_bz2',
        'bz2',
        '_csv',
        'csv',
        '_json',
        'json',
        # --- Windows 兼容性: stdlib 核心 C 扩展 (Iter-26~35) ---
        '_struct',
        'struct',
        '_io',
        'io',
        '_collections_abc',
        'collections.abc',
        '_weakref',
        'weakref',
        '_frozen_importlib',
        '_frozen_importlib_external',
        '_compression',
        '_signal',
        'signal',
        '_thread',
        'threading',
        '_warnings',
        'warnings',
        '_abc',
        'abc',
        # --- Windows 兼容性: 编码模块 (Iter-36~37) ---
        'encodings',
        'encodings.utf_8',
        'encodings.gbk',
        'encodings.ascii',
        'encodings.latin_1',
        'encodings.idna',
        'encodings.aliases',
        # --- Windows 兼容性: 通用 stdlib 模块 (Iter-38~45) ---
        'atexit',
        'errno',
        'faulthandler',
        'gc',
        'itertools',
        'math',
        'operator',
        'platform',
        'traceback',
        'types',
        'typing',
        'typing_extensions',
        'functools',
        'linecache',
        'copyreg',
        'reprlib',
        # --- Windows 兼容性: 高 DPI 感知 (Iter-47) ---
        'ctypes',
        'ctypes.wintypes',
        # --- Windows 兼容性: 临时文件和路径 (Iter-48) ---
        'tempfile',
        'shutil',
        'pathlib',
        'os.path',
        'fnmatch',
        'glob',
        # --- Windows 兼容性: 命令行参数解析 (Iter-49) ---
        'argparse',
        'getopt',
        'gettext',
        'locale',
        'string',
        'textwrap',
        'logging',
        'logging.handlers',
        # --- Windows 兼容性: 底层 C 扩展补全 (Iter-50) ---
        '_collections',
        '_functools',
        '_locale',
        '_stat',
        '_string',
        '_opcode',
        '_pickle',
        'pickle',
        '_posixsubprocess',
        'subprocess',
        'base64',
        'binascii',
        'email',
        'email.mime',
        'email.mime.text',
        'email.utils',
        'http',
        'http.client',
        'http.server',
        'urllib',
        'urllib.parse',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'html',
        'html.parser',
        # --- Windows 兼容性: multiprocessing ---
        'multiprocessing',
        'multiprocessing.popen_spawn_win32',
        'multiprocessing.spawn',
        # --- Windows 兼容性: socket 子模块 ---
        'socket',
        'fcntl',
        # --- Windows 兼容性: pydantic 动态导入 ---
        'pydantic.deprecated.decorator',
        'pydantic.annotated_handlers',
        'pydantic.functional_validators',
        'pydantic.functional_serializers',
        # --- Windows 兼容性: numpy 子模块 ---
        'numpy.core._multiarray_umath',
        'numpy.linalg._umath_linalg',
        'numpy.random._common',
        'numpy.random.bit_generator',
        'numpy.random._bounded_integers',
        'numpy.random._mt19937',
        'numpy.random._pcg64',
        'numpy.random._philox',
        'numpy.random._sfc64',
        'numpy.random._generator',
        # --- Windows 兼容性: scipy ---
        'scipy.spatial.transform._rotation_groups',
        'scipy.spatial.transform._rotation',
        'scipy.sparse.csgraph._validation',
        'scipy.sparse.csgraph._tools',
        'scipy.sparse.csgraph._traversal',
        'scipy.sparse.csgraph._min_spanning_tree',
        'scipy.sparse.csgraph._flow',
        'scipy.sparse.csgraph._matching',
        'scipy.sparse.csgraph._reordering',
        'scipy.sparse.csgraph._shortest_path',
        'scipy.sparse.linalg._dsolve.linsolve',
        'scipy.sparse.linalg._eigen.arpack',
        'scipy.sparse.linalg._isolve.iterative',
        # --- Windows 兼容性: torch ---
        'torch',
        'torch.utils',
        'torch.utils.data',
        'torch._C',
        'torch.nn',
        'torch.nn.functional',
        'torch.optim',
        # --- Windows 兼容性: starlette / fastapi ---
        'starlette.middleware',
        'starlette.middleware.base',
        'starlette.middleware.cors',
        'starlette.middleware.gzip',
        'starlette.middleware.errors',
        'starlette.middleware.httpsredirect',
        'starlette.middleware.trustedhost',
        'starlette.middleware.wsgi',
        'starlette.middleware.sessions',
        'starlette.responses',
        'starlette.routing',
        'starlette.staticfiles',
        'starlette.templating',
        'starlette.concurrency',
        'starlette.convertors',
        'starlette.datastructures',
        'starlette.exceptions',
        'starlette.formparsers',
        'starlette.requests',
        'starlette.status',
        'starlette.types',
        'starlette.websockets',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.middleware.gzip',
        'fastapi.middleware.trustedhost',
        'fastapi.middleware.httpsredirect',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # --- Windows 兼容性: httpx / httpcore ---
        'httpx',
        'httpcore',
        'h11',
        # --- Windows 兼容性: structlog ---
        'structlog',
        'structlog.dev',
        'structlog.processors',
        'structlog.stdlib',
        'structlog.threadlocal',
        # --- Windows 兼容性: pyarrow ---
        'pyarrow',
        'pyarrow.lib',
        'pyarrow._parquet',
        'pyarrow.compute',
        'pyarrow.csv',
        'pyarrow.dataset',
        'pyarrow.feather',
        'pyarrow.fs',
        'pyarrow.json',
        'pyarrow.parquet',
        'pyarrow.types',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除不需要的大型调试/测试/文档模块以减小 EXE 体积
        'pytest',
        'setuptools',
        'pip',
        'wheel',
        'tkinter',
        'unittest',
        'test',
        'tests',
        'docutils',
        'sphinx',
        'IPython',
        'jupyter',
        'notebook',
        'matplotlib',
        'PIL',
        'cv2',
        'tensorflow',
        'keras',
        'tensorboard',
        'sqlalchemy',
        'alembic',
        'pandas.tests',
        'numpy.tests',
        'scipy.tests',
        'pyarrow.tests',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='f1opt',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,  # 默认 console 模式; Windows 下可改为 False 隐藏控制台
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows 特有: 嵌入 UAC manifest (请求管理员权限, 但非强制)
    uac_admin=False,
    uac_uiaccess=False,
    # Windows: 版本信息资源 (Iter-46)
    icon=None,
    version='/workspace/f1opt/version_info.txt' if IS_WINDOWS else None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[
        # 排除不应被 UPX 压缩的文件 (某些 DLL 解压可能触发 AV 误报)
        'python3*.dll',
        'vcruntime*.dll',
        'msvcp*.dll',
        'api-ms-win-*.dll',
        'ucrtbase.dll',
        '_socket.pyd',
        '_asyncio.pyd',
        'select.pyd',
        '_overlapped.pyd',
    ],
    name='f1opt',
)
